### ISSUE TITLE
HU3 -  Crear un álbum

### ISSUE THREAD

**Issue by MariaLu98** [carlostiguaque/MISW-4203-MOVILES#3]
# Descripción
Como coleccionista quiero agregar un álbum al listado para poder tener acceso a él desde la interfaz gráfica de la aplicación. 

# Criterios de aceptación

- Al hacer clic en el botón correspondiente de agregar álbum, los siguientes campos deben ser diligenciados:

    - Nombre, este campo será obligatorio. 
    - Cover,  este campo será obligatorio. 
    - Release Date, este campo será obligatorio.
    - Description, este campo será obligatorio.
    - Genre, este campo será obligatorio. 
    - Record label, este campo será obligatorio. 
 
- Para guardar el álbum, se debe seleccionar el botón guardar. Una vez presionado, se regresará al artista respectivo.
- Para cancelar el proceso, se debe seleccionar el botón Cancelar. Una vez presionado, se regresará al artista respectivo. 
- Se debe poder regresar al "Home" de la aplicación, a través de un botón en la esquina superior derecha. 
- En la parte superior izquierda, se encuentra una imagen que indica la inicial del nombre del usuario logueado.

# Mockup
![image](https://github.com/carlostiguaque/MISW-4203-MOVILES/assets/140918267/1d693d20-e3d3-4460-8f11-d850dc2b29a3)

# Tareas:

- [x] #38
- [x] #39
- [x] #40
- [x] #41
- [x] #42
- [x] #43
- [x] #44
- [x] #45

**Comment by jvillada97** [comment]
# Mockup
![image](https://github.com/carlostiguaque/MISW-4203-MOVILES/assets/142458103/dd36cd3f-f3db-4bea-8fa7-cc6eb478eebe)
